### PR TITLE
Add new tutorial to production

### PR DESCRIPTION
**Pull request by beapasch**
Add new tutorial to production

### CODE REVIEW

**Review by thecodester — CHANGES_REQUESTED** [review]
- Title should be title case
- Please add border around images -- just add a second ! in the MD coding
- Description could be more description and should end in period
- Always put a blank line before and after images
- Step 8 (and elsewhere), don't start note with "Note:", just write the note.
- Step 9 (and maybe elsewhere), there are no blank lines between the sentences so they run together. In general, since there aren't a lot of words on the page, you can break up each action and put in new paragraph.
- Add one more choice to the question in Step 9.
- Step 1 in first sentence, put comma after "account" and generally when you start with a dependent clause.
- Step 4, I would put the sentence with the action ("Choose ...") in its own paragraph.
- Step 5, I would avoid "Finally", and then make the sentence something like "you can specify advanced settings, and do not use "e.g.", spell out for example, and put the action on its own paragraph.

Thanks, Daniel

**Comment by beapasch** [comment]
I did all the changes

**Comment by thecodester** [comment]
Thanks for the update:

- I still see the title as not title case.
- The phrase "Learn how easy it is to ..." should be removed and just say what they will do (i.e., "Translate a properties file ..."
- I didn;t really understand the description -- is "file upload - translation workflow" a thing? I didn;t really understand. Also, "from" STH to me is a little strange -- is the tool part of STH? "from" just makes it sound like STH is some company that is sponsoring this capability. Is this capability part of another tool? I feel I don;t really get enough context.

Feel free to set up a short call if my comments don't make sense or are not clear.

**Comment by beapasch** [comment]
I did all the necessary changes

**Pull request merged**
