### PR TITLE
starter scenario update new layout

### PR DESCRIPTION
**Pull request by mervey45**
Hi @thecodester ,

this is an update on the starter scenario. Please publish this only, when @AnnikaGonnermann gives her go. 

Thank you.

Best regards, 
Merve

### CODE REVIEW

**Comment by mervey45** [comment]
Here is an update on the starter scenario

**Comment by thecodester** [comment]
@mervey45 The email that you are committing with for the last few commits -- merve.temel@dsap.com -- is different than email of your account. That's why the PR shows you not having completed the CLA. Please adjust your Git client.

**Comment by MichaelCzcz** [comment]
@mervey45 Could you please solve those conflicts and sign the CLA? Thank you.

**Comment by mervey45** [comment]
Hi @thecodester ,

I updated my e-mail address in github (browser) and set it via command line. Do I need to do something else? 

Best regards, 
Merve

**Comment by thecodester** [comment]
When you commit -- using the locally installed Git -- an email and name is attached to the commit. You can see this in your last commit to production: https://github.com/SAPDocuments/Tutorials/commit/f7c0f0bbe86d7d11908f11c78860b3932bc0d150.patch

This name and email are determined by your Git settings on your desktop. If you look at the installation instructions in my tutorial for authors, you will see this as one of the steps.

But if you sign into GitHub with an account with a different email address, then GitHub will not match the author of your commit (you but different email address) to your GitHub account.

So you must set you local Git settings with the same email address as your GitHub account.

**Comment by mervey45** [comment]
Hi @thecodester,

I did this. I added merve.temel@sap.com as my primary e-mail address in my github account and also set it via command line in my local github settings. Before that I used the following e-mail address merve.yalcin@sap.com. Do I need to do something else? 

Best regards, 
Merve

**Comment by thecodester** [comment]
No, I think that's it -- as long as they match. I think locally you had a typo going to dsap.com.

**Comment by mervey45** [comment]
Hi @MichaelCzcz, 

can you mergen my changes. I also signed the CLA.

Thank you.

Best regards, 
Merve

**Pull request merged**
