### PR TITLE
Updating SAP Mobile cards starter mission

### PR DESCRIPTION
**Pull request by shahchetali**
I have modified the Welcome tutorial to improve the starter scenario and a new tutorial is created to showcase the power of SAP Mobile Cards.

### CODE REVIEW

**Review by thecodester — CHANGES_REQUESTED** [review]
Let's discuss changes to mission offline

**Comment by sandeep-tds** [comment]
Hi @thecodester, 

Chetali is on leave, and we had to incorporate changes suggested by Annika.
Thus, I've updated the tutorials and created a new PR (#6223).

Can you please close this PR and process #6223? 

Thank you for your support.

**Comment by thecodester** [comment]
@sandeep-tds @shahchetali I do not see the tutorial in QA; I don;t know why.

Please fix the step names as follows:

The real-world use case
Create contact card using boosters
Open card In Mobile Services cockpit
View card on your mobile device

**Comment by thecodester** [comment]
Closing at request of Sandeep

**Pull request closed without merging**
