### PR TITLE
Automatic commit: Move 'cp-enterprisemessaging-instance-create' from …

### PR DESCRIPTION
**Pull request by pradeeppanda-sap**
…QA to Production

needed to remove support in TRIAL environment, as "default" type of  enterprise message is now not available in trial environment. Recent decision.

### CODE REVIEW

**Comment by thecodester** [comment]
Are you saying it does not work on trial environment?

Also, I think SAP Cloud Platform (Cloud Foundry) environment is not quite right. IT is "SAP Cloud Platform, Cloud Foundry environment"

**Comment by pradeeppanda-sap** [comment]
Added SAP Cloud Platform, Cloud Foundry environment as per feedback and committed few images by beautifying little bit.

**Comment by thecodester** [comment]
I still don't understand. The tutorial does not work in trial environment. If so: 

- I don't think people will understand by what you wrote that it does not work on trial
- Non-trial tutorials must be marked with the tutorial>license tag as requiring a customer license

**Comment by pradeeppanda-sap** [comment]
Hi Daniel,
  As per your advise, i have introduced the tutorials>license tag for the hands on exercise tutorials. 
  Just to clarify, earlier the enterprise message instance creation was working on trial environment. But due to some technical issue, it has been stopped. Hence it is not going to work on trial environment now.
Also some changes have been made in json file as per the new changes done by the product team which has been updated in the cp-enterprisemessaging-instance-create tutorial.

Hope it clarifies your queries and we are good to go :).

regards
Pradeep

**Pull request merged**
