### PR TITLE
Enhance Project Configuration for SAP HANA

### PR DESCRIPTION
**Pull request by iwonahahn**

### CODE REVIEW

**Review by thecodester — CHANGES_REQUESTED** [review]
The indenting at least in cap-service-deploy is not correct -- please look at the preview and see the substep restarts:

image

Please correct.

**Comment by iwonahahn** [comment]
@thecodester thanks for the hint, It took me a while to fix it 😅 .

**Comment by thecodester** [comment]
I will merge, but there is still an indent issue on the final code block of the different steps. Please correct in a subsequent update.
image

**Comment by iwonahahn** [comment]
@thecodester thanks for merging. Will have a look later today.

**Pull request merged**
