### PR TITLE
Updates to Tour the SAP Community tutorial

### PR DESCRIPTION
**Pull request by WorkJerryJanda**

### CODE REVIEW

**Comment by WorkJerryJanda** [comment]
I took out the spaces because in preview, the image looked pushed all the way to the right. (The current image is more horizontal. The new one is more vertical.)
I'll put the spaces back.
Will also remove note.

**Comment by thecodester** [comment]
Jerry, no need to close the PR. When you make an update to your fork it is reflected in the PR. But closing and creating from scratch is OK, too.

**Comment by WorkJerryJanda** [comment]
I just made the changes and confirmed them in QA. You're saying I don't need to push to production? Or I should, but I don't have to create a pull request?

**Comment by WorkJerryJanda** [comment]
I'm confused because it states that pull request is closed, so I'm not sure what I need to do here.

**Comment by thecodester** [comment]
You always have to work in QA, and when finished push to production. 

If you don't have an open PR then you need to create one.

So in this case, since you had an open PR, you could have just pushed to production and the changes would have been reflected in the existing PR. But since it is now closed -- no worries -- you need to create a new one (after pushing to production).

**Comment by WorkJerryJanda** [comment]
Understood. Doing all that now.

**Pull request closed without merging**
