### PR TITLE
PR with updated tutorial

### PR DESCRIPTION
**Pull request by LakshmiCR**
Changes - adapted to cds watch, and other minor modifications
Note: Image changed to new-cds-commands.PNG. Please check if this image is fine for the tutorial

### CODE REVIEW

**Comment by iwonahahn** [comment]
@LakshmiCR & @lalithmanokar : Thanks for the changes, please sign the CLA as mentioned above. I´ll do a review of course, but only Daniel can approve this PR.

**Comment by iwonahahn** [comment]
@thecodester : Could you please approve this PR that we can review the content on QA with the dev team? THANKS

**Comment by thecodester** [comment]
You are trying to update the production repo without updating the QA repo first. Please contact me offline if you need help.

**Comment by iwonahahn** [comment]
@thecodester Will do the changes provided in this PR on QA first. @LakshmiCR & @lalithmanokar: once the changes are on QA I´ll let you know so we can final review the content.

**Comment by thecodester** [comment]
You may want to use the Atom plugin that we provide which makes committing and pushing much easier.

**Comment by chgeo** [comment]
Looks good to me content-wise

**Pull request closed without merging**
