### PR TITLE
changes on tutorials + 1 new tutorial

### PR DESCRIPTION
**Pull request by mervey45**
Hi @thecodester could you please publish these changes today? I have a new tutorial and had to update 2 other tutorials.

Best regards, 
Merve

### CODE REVIEW

**Comment by mervey45** [comment]
I've changed it on qa already, do I need to republish it again?
image

**Comment by mervey45** [comment]
Hi @thecodester, 

I've updated all tutorials.

Thank you.

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @thecodester, 

the images aren't shown. Is this still a cache problem or do I need to republish again?
image

Thank you.

Best regards, 
Merve

**Comment by thecodester** [comment]
I see them. Yes, it can take a few minutes.

**Pull request merged**
