### PR TITLE
updated screenshots and content for iot-express-4a tutorial

### PR DESCRIPTION
**Pull request by JitendraSharma01**

### CODE REVIEW

**Comment by JitendraSharma01** [comment]
changed the title/resolved review

**Comment by thecodester** [comment]
@JitendraSharma01 I see you are not using the Atom plugin to author. I highly recommend -- even insist -- you use it. This will help you preview, validation, and push your tutorials with a single click (sometimes automatically), and keep the QA and production repos in sync. The last commit is not in QA.

**Comment by JitendraSharma01** [comment]
> @JitendraSharma01 Can you modify the title and description. The title is VERY generic and it is not clear what it refers to. Perhaps even adding the word "Thing" or "IoT" would help. The description should better mention the technology you are refrring to -- this helps explain to someone what the tutorial is about and helps with SEO.



> @JitendraSharma01 I see you are not using the Atom plugin to author. I highly recommend -- even insist -- you use it. This will help you preview, validation, and push your tutorials with a single click (sometimes automatically), and keep the QA and production repos in sync. The last commit is not in QA.



> @JitendraSharma01 I see you are not using the Atom plugin to author. I highly recommend -- even insist -- you use it. This will help you preview, validation, and push your tutorials with a single click (sometimes automatically), and keep the QA and production repos in sync. The last commit is not in QA.

Hi ,
I am using the sap plugin, also I made the QA repo in sync as it was in my fork before. I had some issue while using the plugin to push, however validation and other things worked fine. It is because of my local git repo configurations hence created through a fork.

**Comment by JitendraSharma01** [comment]
i am trying my local config again so would like to close this PR

**Comment by JitendraSharma01** [comment]
using sap-plugin again to push to Prod environment so closing this PR to be clear

**Pull request closed without merging**
