### PR TITLE
[DO NOT PUBLISH BEFORE FEB. 16!]: UI Changes and renaming of SCP to BTP

### PR DESCRIPTION
**Pull request by mjeann**
Please do not publish this PR before February 16th.
The UI Changes are published (to my knowledge) on this day.
UI Changes for Subscriptions page -> Service Marketplace.

### CODE REVIEW

**Review by MichaelCzcz — APPROVED** [review]

**Comment by mjeann** [comment]
Please don't merge PR before Feb. 16!

**Comment by thecodester** [comment]
FYI: We will be adjusting the tags which may require you to change the tags in the tutorial, so you may have to resubmit the PR with the adjusted tags. Will send email later today I hope.

**Comment by mjeann** [comment]
Could you commit this today?
I guess the tag changes are not yet mandatory, or are they?

**Comment by mjeann** [comment]
changed the btp tags
It is ready for merge now

**Pull request merged**
