### PR TITLE
Minor edit to question about tags

### PR DESCRIPTION
**Pull request by WorkJerryJanda**

### CODE REVIEW

**Comment by thecodester** [comment]
@mstmustisnt This PR shows no changed files. Do I need to merge? What is going on?

@WorkJerryJanda This PR shows no changed files. Do you mean to change something?

**Comment by mstmustisnt** [comment]
@thecodester please see
https://github.com/SAPDocuments/Tutorials/pull/4741/files

this PR has the same changes (compare a commit from this PR https://github.com/SAPDocuments/Tutorials/pull/4827/commits/f846d41fb51b78e2e6af4c93feb186a08b3474c3 and https://github.com/SAPDocuments/Tutorials/pull/4741/files), and it was merged. You can close this PR.

**Comment by mstmustisnt** [comment]
> Automatic commit: Move 'community-profile' from QA to Production
> 
> @WorkJerryJanda
> WorkJerryJanda committed 22 days ago


This commit was merged to master in #4741 22 days ago

**Comment by thecodester** [comment]
thanks

**Pull request closed without merging**
