### PR TITLE
BTP name/tag changes and UI changes related to Subscriptions page

### PR DESCRIPTION
**Pull request by Karunaharan**

### CODE REVIEW

**Review by MichaelCzcz — CHANGES_REQUESTED** [review]
Please stick to the [style guide](https://jam4.sapjam.com/wiki/show/MozDWaPczznL8NKeGEk0y9?_lightbox=true#mcetoc_1dtvf3pb64) for image file names.

**Comment by Karunaharan** [comment]
Hi @MichaelCzcz - do you want me to send new PR after making the changes? Please let me know

**Comment by MichaelCzcz** [comment]
Just push your changes please.

**Comment by Karunaharan** [comment]
Pushed the changes now

**Comment by Karunaharan** [comment]
@MichaelCzcz @thecodester - are there any changes that are pending from my side? Please let me know when you can publish these changes.

**Comment by MichaelCzcz** [comment]
@Karunaharan there are still file names that have dots and/or spaces. Please correct them.

**Comment by MichaelCzcz** [comment]
image

**Comment by Karunaharan** [comment]
I have rechecked and fixed the file names that had dots/spaces

**Comment by MichaelCzcz** [comment]
There are still many file names with dots. Please remove/replace those dots. 
Example: Instead of "1.3.create-new-instance.png" you should name this particular file "1-3-create-new-instance.png".

**Comment by Karunaharan** [comment]
@MichaelCzcz - there are lot many like this from a long time. In **_1.3.create-new-instance.png_**, 1.3 is the step number which we maintained like this from a long time. Will change all these and push them together

**Comment by Karunaharan** [comment]
I have now renamed all the images in the 3 tutorials as per the styleguide

**Pull request merged**
