### PR TITLE
adding node js tutorial to be released on Tuesday Nov 27

### PR DESCRIPTION
**Pull request by Chuergo**
This tutorial should be released on Tuesday, Nov 27 (with product release). I will add Christian Georgi as a reviewer to this pull request to confirm (depends on product release).

### CODE REVIEW

**Comment by thecodester** [comment]
Is this ready?

**Comment by Chuergo** [comment]
Not yet. Christian will confirm via the review feature and then you can publish.

**Comment by chgeo** [comment]
We are in the last miles of pushing the release out.  As soon as this happens, I will give you a ping here.

**Comment by chgeo** [comment]
When will this be live?

**Comment by Chuergo** [comment]
@thecodester you said the production server is updated once a day, right? What time is it updated? Do we need to wait until tomorrow to see this tutorial? If so, can we publish "ad hoc"?

**Pull request merged**
