### PR TITLE
renaming and new tutorial

### PR DESCRIPTION
**Pull request by mervey45**
-

### CODE REVIEW

**Comment by thecodester** [comment]
Niloofar is again added as author of the tutorial. Again, I would use the plugin. If not, you need to make sure you are syncing the repos correctly.

**Comment by mervey45** [comment]
@thecodester Unfortunately I get an error message, when I try to use the plug-in.

image

Do you know, what I can do there?

Thank you.

Best regards, 
Merve

**Comment by mervey45** [comment]
@thecodester Can you publish all 3 tutorials by tomorrow? 
Thank you.

Best regards, 

Merve

**Comment by thecodester** [comment]
There are 2 tutorials with the exact same titles and description. Why is that?

abap-environment-s4hanacloud
abap-environment-s4hanacloud-binding

**Comment by mervey45** [comment]
There are 3 tutorials with the **abap-environment-s4hanacloud** naming. They belong together, that's why I named them like following: 

- abap-environment-s4hanacloud
- abap-environment-s4hanacloud-binding
- abap-environment-s4hanacloud-service-consumption

The first one is abap-environment-s4hanacloud and then the other 2 tutorials follow.

**Comment by mervey45** [comment]
@thecodester I updated the service binding tutorial, now they have different titles and descriptions

**Pull request merged**
