### PR TITLE
Implementing feedback from BTP starter scenario testing team

### PR DESCRIPTION
**Pull request by Karunaharan**
Implementing feedback from BTP starter scenario testing team

### CODE REVIEW

**Review by MichaelCzcz — CHANGES_REQUESTED** [review]
Images may not be published when there is no change to the md-file.
Please add a space somewhere in the md-file where it doesn't matter.

**Comment by Karunaharan** [comment]
@MichaelCzcz I have made a minor change to the .md file now.

**Comment by MichaelCzcz** [comment]
@Karunaharan Can you please push them?

**Comment by Karunaharan** [comment]
Yes, I have pushed them

**Pull request merged**
