### PR TITLE
update develop fiori app mission

### PR DESCRIPTION
**Pull request by mervey45**
Hi @thecodester ,

Otilia wanted to have a look at it as well, but she will return on Monday. @otiliamarinescu  I couldn't link the steps within the tutorial. But besides that, I hope I have taken all changes into account. If not, feel free to give me feedback.

Thank you.

Best regards, 
Merve

### CODE REVIEW

**Comment by thecodester** [comment]
@mervey45  THE PR shows a conflict. Can you resolve?

**Comment by mervey45** [comment]
@thecodester I just copied the Trial Onboarding Tutorial in my fork folder and pushed it again. Is the conflict solved now?

**Comment by thecodester** [comment]
IT shows in the PR there is a conflict. You can resolve it in the UI of GitHub.com (right here)

**Comment by mervey45** [comment]
I solved the conflict, but do I need also to click on commit merge?

**Comment by thecodester** [comment]
You need to commit the changes so the PR is updated

**Comment by mervey45** [comment]
Thank you, Daniel. I committed my changes.

**Pull request merged**
