### PR TITLE
Modified for rebranding and merging 3 tutorials into 1

### PR DESCRIPTION
**Pull request by ArchanaShukla**
…'cp-starter-ibpm-employeeonboarding-2-businessrules', 'cp-starter-ibpm-employeeonboarding-2-configure', 'cp-starter-ibpm-employeeonboarding-3-workflow', 'cp-starter-ibpm-employeeonboarding-4-visibility', 'cp-starter-ibpm-employeeonboarding-5-run' from QA to Production

### CODE REVIEW

**Review by thecodester — CHANGES_REQUESTED** [review]
If we are merging 3 tutorials into 1, what is happening with the original 3? Do we delete? What about any group/mission? Will the new one be not too long?

**Comment by ArchanaShukla** [comment]
@thecodester - Yes, previous 3 will be deleted. The existing group have to be adapted to show only 3 tutorials now. No its is not very long. This has been done as feedback to improve the mission completion rate.

**Comment by thecodester** [comment]
If you can send me an email (offline) and just tell me exactly what you want me to do to the group/mission, that would be good.

**Comment by thecodester** [comment]
Working with Archana offline. Closing this PR.

**Pull request closed without merging**
