### PR TITLE
Automatic commit: Move cp-mobile-dev-kit-create-customer, cp-mobile-d…

### PR DESCRIPTION
**Pull request by jitendrakansal**
resized some of existing images

### CODE REVIEW

**Comment by jitendrakansal** [comment]
@thecodester sure I will do that .
Just to understand it more clear- do I need to make changes to all MD files (tutorials associated with this PR) or either one is fine ?

**Comment by thecodester** [comment]
You need to touch every MD that includes an image that you are updating/adding/removing.

**Comment by jitendrakansal** [comment]
@thecodester i now updated MDs with some text, does it work now?

**Comment by thecodester** [comment]
Next time you can just add a space somewhere -- that's good enough :-)

**Pull request merged**
