### PR TITLE
Automatic commit: Move cp-mobile-dev-kit-add-validation from QA to Pr…

### PR DESCRIPTION
**Pull request by jitendrakansal**
MDK tutorial

### CODE REVIEW

**Comment by jitendrakansal** [comment]
there was one image somehow get deleted and i was not able to restore it. I had to capture it again. 

Can you hold this PR for today? i have some more tutorials to push to PROD, i can combine it with existing one. ok with you?

**Comment by thecodester** [comment]
I will review Sunday. Are we creating a group? How do these relate to your existing mission?

**Comment by jitendrakansal** [comment]
There will be a new group for these tutorials (except MDK online one ) targeting intermediate level MDK development.  I am currently working on two more tutorials going to be part of this group. Meanwhile, I will send you group details in a separate email.

**Comment by jitendrakansal** [comment]
@thecodester : did you already review it?

**Pull request merged**
