### PR TITLE
new CAP tutorials for SAP BTP Application development mission

### PR DESCRIPTION
**Pull request by iwonahahn**
see my email for the 18 new tutorials

### CODE REVIEW

**Comment by iwonahahn** [comment]
> see my email for the 18 new tutorials

now only 17 cause we removed the SAP Business Application Studio tutorial

**Comment by thecodester** [comment]
@iwonahahn I see 18 new tutorials (plus 2 to be updated), but you said there should be 17. I suggest you close this PR, reset your fork (there's a button in plugin, takes a few minutes but wait until complete) and then push the 17+2 tutorials and create new PR.

**Review by thecodester — CHANGES_REQUESTED** [review]
See previous comment

**Comment by iwonahahn** [comment]
will open a new one

**Pull request closed without merging**
