### PR TITLE
SAC Tutorial

### PR DESCRIPTION
**Pull request by imtiyaz-s**

### CODE REVIEW

**Review by MichaelCzcz — CHANGES_REQUESTED** [review]

**Comment by imtiyaz-s** [comment]
Update the changes as suggested

**Comment by thecodester** [comment]
The only problem with updating here is that the changes are lost on QA, and the next time someone republishes the tutorial your changes will be lost. The process is to make changes in QA and push to production, using Atom plugin, which is real easy. You can manual do it if you prefer, but you have to keep QA and production up to date.

**Comment by imtiyaz-s** [comment]
> The only problem with updating here is that the changes are lost on QA, and the next time someone republishes the tutorial your changes will be lost. The process is to make changes in QA and push to production, using Atom plugin, which is real easy. You can manual do it if you prefer, but you have to keep QA and production up to date.

Hello Daniel,
After pushing changes to Production, it says :You must create a PR using this link" 
image
Regards, Imtiyaz

**Comment by thecodester** [comment]
Im not sure what you are trying to say. Please set up meeting with me to clarify.

**Pull request merged**
