### PR TITLE
Tutorial to integrate SAP Cloud SDK into CAP 

### PR DESCRIPTION
**Pull request by nabilshafi1**

### CODE REVIEW

**Comment by nabilshafi1** [comment]
Please review it asap. @thecodester

**Review by thecodester — CHANGES_REQUESTED** [review]
-- Can you add additional detail into the description -- don;t just repeat the title. Here's your chance to add context.
-- Some of the codeblocks have extra line at start or end -- please remove.
-- You have a step called Read and write methods --> do you mean the step is to create read and write methods? If so, make the step start with a verb

Thanks

Daniel

**Comment by nabilshafi1** [comment]
> -- Can you add additional detail into the description -- don;t just repeat the title. Here's your chance to add context.
> -- Some of the codeblocks have extra line at start or end -- please remove.
> -- You have a step called Read and write methods --> do you mean the step is to create read and write methods? If so, make the step start with a verb
> 
> Thanks
> 
> Daniel

- I have modified the description.
- In step 3, there is an UI issue in a codeblock could you please have a look.
- I just want to explain read and write method.

**Comment by thecodester** [comment]
Please see comments emailed to you

**Comment by MatKuhr** [comment]
Hi Daniel, please put any comments you might have either here or send them to me per email. Thanks!

**Comment by MatKuhr** [comment]
Please close this in favor of #5835

**Pull request closed without merging**
