### PR TITLE
CBO tutorials: layout repairs incl. not working DONE button

### PR DESCRIPTION
**Pull request by Liebherr**

### CODE REVIEW

**Comment by thecodester** [comment]
Did you mean to make all these changes or was this to add the missing DONE button?

**Comment by Liebherr** [comment]
Hi Daniel,
yes the changes were intended, only the title change I was not aware of and I ask myself how this could happen, might there be a process issue? If I get it right, that title change from before unwillingly reverted my last came with https://github.com/SAPDocuments/Tutorials/commit/9eb8fbc11afc59d936bd2a32bdc55245d9369581#diff-099e427a4cba2813f629cd5e2f0f2820
But I cannot find a corresponding commit in Contribution, so how shall such central changes get there?

Regarding the indenting and other layout issues I will check how to preview and comment/approve/request changes to your proposed changes. Might contact you for this again.

Thanks and Regards
Ulrike

**Comment by thecodester** [comment]
I think it probably my fault. You made a PR request 2 months ago, and I fixed certain things -- like title casing -- but I fixed it only in your PR and not back in the QA version.

**Comment by Liebherr** [comment]
Hi Daniel,
additionally to the changes in CBO group I have finished major reqoek in Custom UI group now.
Regards
Ulrike

**Pull request merged**
