### PR TITLE
Please publish

### PR DESCRIPTION
**Pull request by Paolaufer**

### CODE REVIEW

**Comment by thecodester** [comment]
As the title of the pull request, write what you are pushing. Don;t write "Please publish" since that applies to every PR :-)

**Comment by MichaelCzcz** [comment]
@Paolaufer Can you please resolve the conflicts? Thank you.

**Comment by thecodester** [comment]
The only change here is a reversal of a change I made. I will close the PR. 

@Paolaufer Make sure to pull and fetch the latest version of the QA database -- close and reopen Atom or click fetch, then pull.

**Comment by Paolaufer** [comment]
Thank you!!

**Pull request closed without merging**
