### PR TITLE
Updated S/4HANA integration tutorial

### PR DESCRIPTION
**Pull request by JijoRoyJacob**
Updated the project details image

### CODE REVIEW

**Comment by thecodester** [comment]
ALl I see is removing project-details.png. But doesn't the MD file still have a link to this?

If I made a mistake and you are exchanging pictures, you will need to also make a change to the MD file -- the tutorial needs to be regenerated when updating pictures.

**Comment by JijoRoyJacob** [comment]
> ALl I see is removing project-details.png. But doesn't the MD file still have a link to this?
> 
> If I made a mistake and you are exchanging pictures, you will need to also make a change to the MD file -- the tutorial needs to be regenerated when updating pictures.

Hi Daniel,
Yes, the intent was to update the image. After I replaced the image in the Tutorials-Contribution repository, I performed a Push Tutorial to Production on the tutorial folder. Please let me know how to regenerate the tutorial.

Best regards,
Jijo

**Comment by thecodester** [comment]
OK, I think it is actually updating the picture in GitHub, not merely deleting it. But if you look on the QA website you will see the image did not get updated. You need to make any small change -- add a space -- and then the images will be regenerated for the page.

**Comment by JijoRoyJacob** [comment]
> OK, I think it is actually updating the picture in GitHub, not merely deleting it. But if you look on the QA website you will see the image did not get updated. You need to make any small change -- add a space -- and then the images will be regenerated for the page.

That's strange, because I can see that the image is updated in the QA version of the tutorial. Also when I look at the committed change in detail, this is what I see:
committed

This looks right.

**Pull request merged**
