### PR TITLE
Rebrand

### PR DESCRIPTION
**Pull request by ShiraManas**

### CODE REVIEW

**Comment by MichaelCzcz** [comment]
@ShiraManas Please sign CLA

**Comment by ShiraManas** [comment]
Signed the CLA.

**Review by thecodester — CHANGES_REQUESTED** [review]
Welcome back :-)

On first reference the name of the entity is SAP BTP, Cloud Foundry environment. Can you use that instead?

**Comment by ShiraManas** [comment]
> Welcome back :-)
> 
> On first reference the name of the entity is SAP BTP, Cloud Foundry environment. Can you use that instead?

Really? Paola said that in the tutorials, we should use the full name for the first mentioning of BTP, with BTP in parenthesis.

**Comment by thecodester** [comment]
She is right, but the full name according to branding is SAP BTP, Cloud Foundry environment.

It does say to spell out BTP somewhere later -- not the whole name, mind you, but just BTP part -- , but I do not think this is for the most part necessary, but up to you.

**Comment by thecodester** [comment]
@ShiraManas We are now able to update the tags - can you just do that and I will merge all together? No need for another PR.

**Comment by ShiraManas** [comment]
> @ShiraManas We are now able to update the tags - can you just do that and I will merge all together? No need for another PR.

Hi. I pushed the changes with the updated tags. 
Thanks,
Shira

**Pull request merged**
