### PR TITLE
Create Migration Tutorial for 3.0 of Java Cloud SDK, Update Security on CF with Cloud SDK

### PR DESCRIPTION
**Pull request by MatKuhr**
Creates the following tutorial:

- [Migration Tutorial for 3.0 of Java Cloud SDK](https://developers-qa.sap.com/tutorials/s4sdk-migration-v3.html)

Updates the following tutorials:

- [Secure Your Application on SAP Cloud Platform Cloud Foundry](https://developers-qa.sap.com/tutorials/s4sdk-secure-cloudfoundry.html)
- [Set Up Your Local Infrastructure to Develop with SAP Cloud SDK](https://developers-qa.sap.com/tutorials/s4sdk-setup.html)

### CODE REVIEW

**Comment by MatKuhr** [comment]
Also this fixes #3841. The issue can be closed once this PR is merged.

**Comment by MatKuhr** [comment]
I added the changes back into the s4sdk-secure-cloudfoundry tutorial. I had issues with the atom plugin and believe they were lost in the process of resolving these. 

Also I added links in the prerequisites to other tutorials that cover what is needed for the migration tutorial. But I noticed that currently the migration tutorial is not appearing on QA anymore (tutorial is not found at all). I tried re-uploading it, so far to no avail.

**Comment by thecodester** [comment]
I will check issue with QA

**Comment by thecodester** [comment]
The tutorial is now in both production and QA -- sometimes the system needs a rest :-)

**Pull request merged**
