### PR TITLE
Update image names and type according to guidelines

### PR DESCRIPTION
**Pull request by raz-korn**

### CODE REVIEW

**Review by thecodester — CHANGES_REQUESTED** [review]
This seems like the exact same PR as what we just merged???

**Comment by raz-korn** [comment]
Perhaps a bug in Atom - A request to create PR appeared in Atom after making all the pushes to production.

**Comment by thecodester** [comment]
OK I will close -- I did spot check on several changes and the other PR seems to be OK. Can you reset your fork: In Atom, click Tutorial Helper --> Reset Fork. Thanks.

**Comment by raz-korn** [comment]
Reset fork - done.

**Pull request closed without merging**
