### PR TITLE
abap-environment-abapgit: update urls

### PR DESCRIPTION
**Pull request by larshp**

### CODE REVIEW

**Review by MichaelCzcz — CHANGES_REQUESTED** [review]
Please adjust the tags to use the new brand names.

**Comment by larshp** [comment]
ohem, okay, I have no idea about the SAP brand names, note that I am an external contributor, not affiliated with SAP

is there an overview of the old vs new tags?

**Comment by MichaelCzcz** [comment]
@larshp We appreciate your good intentions, thank you. Please note that only the authors make changes to their tutorials. If you encounter errors or issues with one of our tutorials, please use the "provide feedback" feature in that particular tutorial.

image

**Comment by thecodester** [comment]
@larshp We have reopened the PR and assigned to the author, who will handle when returning from a short leave. Can I ask you what is your relationship to this tutorial, that is, why did the author reference your GitHub account/repo? Should we have referred to the ABAPgit account or is that something new?

**Comment by larshp** [comment]
the URL moved to abapGit/abapGit in September 2020, https://twitter.com/LarsHvam/status/1309057808298631169, just updating to reflect the change

Note that the old url still works, but redirects to the new

**Review by niloofar-flothkoetter — APPROVED** [review]

**Comment by niloofar-flothkoetter** [comment]
Hi all,
Thanks Lars for your info.
@MichaelCzcz should I create a new PR with these changes and update Tags too?

**Comment by thecodester** [comment]
@niloofar-flothkoetter  I will merge this PR, but please make the changes in QA version and update the tags, and create a new PR for those. Thanks.

**Pull request merged**
