### PR TITLE
Automatic commit: Move 'iotae-api-postman' from QA to Production

### PR DESCRIPTION
**Pull request by banurekhabalaji**
The broken link to the previous tutorial is fixed now

### CODE REVIEW

**Review by thecodester — CHANGES_REQUESTED** [review]
The second item in the You will learn that you added just says the same as the first. Either remove or move this line to the intro -- just skip a line in the MD file and remove the bullet and move flush left

**Comment by banurekhabalaji** [comment]
Edited the "You will learn" section

**Comment by thecodester** [comment]
Sorry I wasn't clear -- every tutorial has at least one "You will learn" item with a bullet, no period at the end.

I recommend this:

```
- How to Use Postman to access SAP IoT APIs

In [previous tutorials](iot-express-4-create-thing-model), you learned about using Thing Modeler to onboard a thing, send data to the thing, and retrieve data from the thing. Now, you'll learn to use Postman to access SAP IoT APIs.
```

Also, all links to other tutorials/groups/missions have a shortened syntax. See above for tutorial example, and groups are [AAA](group.cp-group-name) and missions are [AAA](mission.cp-group-name). Please fix in your tutorials.

**Comment by thecodester** [comment]
@banurekhabalaji Can you make change and I will then merge?

**Comment by banurekhabalaji** [comment]
@thecodester I will make the changes and keep you informed. Thank you.

**Comment by banurekhabalaji** [comment]
This tutorial should be added to the group - https://developers.sap.com/group.iot-geomatching.html.

**Comment by thecodester** [comment]
The You will learn section still not a bulleted list. Also, where should this go in the group?

**Comment by banurekhabalaji** [comment]
@thecodester, the WebIDE plugins removed from two tutorials, the reference tutorial links are corrected (mission.AAA and group.AAA), you will learn section too updated. Hope, I covered all your comments this time.

**Comment by banurekhabalaji** [comment]
@thecodester,  Updated the title for the group

**Pull request merged**
