### PR TITLE
Fix Issue #4512

### PR DESCRIPTION
**Pull request by juancarlosrodriguezf**
Fix Issue #4512
Call an External Endpoint to Retrieve Additional Information
https://github.com/SAPDocuments/Tutorials/issues/4512

### CODE REVIEW

**Review by MichaelCzcz — CHANGES_REQUESTED** [review]
Your changes are OK, but there are still Cloud Platform tags in your tutorial. Please update the tags.
Also, please make sure that your Github account is linked to the [Open Source Portal](https://jam4.sapjam.com/groups/A7NmsKmoG9vVaxizKhdQOk/overview_page/jpJF7KXn5B2tFFQVOQ1Ybm).

**Comment by juancarlosrodriguezf** [comment]
Hi @MichaelCzcz , I'm not the owner of the course, I'm only trying to fix an error in a tutorial that I've done and I try to colaborat.

**Comment by MichaelCzcz** [comment]
@juancarlosrodriguezf Thanks for the heads up. Could you please align with the tutorial's owner then? Thank you.

**Comment by MichaelCzcz** [comment]
@gauthamkrishna-sap Please discuss changes to your tutorial with @juancarlosrodriguezf.

**Comment by thecodester** [comment]
@juancarlosrodriguezf Thanks for the contribution.

@gauthamkrishna-sap Please handle this quickly. I have changed in this PR (but not in QA) the tags to plain BTP. My understanding is that the current primary tag -- primary_tag: products>sap-cloud-platform-integration-for-process-services
 -- is no longer used.

**Comment by gauthamkrishna-sap** [comment]
Hi @juancarlosrodriguezf ,
Thank you so much for taking the time to contribute to this tutorial. Unfortunately , this is outdated and we are working to replace this with a new and updated series. This tutorial will be taken down shortly. Please stay tuned for further updates. 
In the meantime, you can try out this tutorial series: https://github.com/SAP-samples/teched2020-DEV165
Thanks and Best Regards,
Gautham

**Pull request closed without merging**
