### PR TITLE
Modified the wrong image

### PR DESCRIPTION
**Pull request by ArchanaShukla**

### CODE REVIEW

**Comment by MichaelCzcz** [comment]
@ArchanaShukla did you just delete one image? If you want to replace it you need to make a simple change to the -md-file, like adding a space somewhere where it doesn't hurt.

image

**Review by thecodester — CHANGES_REQUESTED** [review]
See Michael's comment

**Comment by ArchanaShukla** [comment]
hello Michael, by mistake named a wrong image to the one mentioned in the tutorial. I have just deleted the old one as that was not needed and added the right image with the same name. Thanks for the comment. Will do that next time.

**Comment by thecodester** [comment]
The PR has 1 file changed, the image. But images do not get updated unless you make any update to the MD file, just add a space

**Pull request closed without merging**
