### PR TITLE
update naming 2 tutorials

### PR DESCRIPTION
**Pull request by mervey45**
@thecodester 
Hi Daniel, 

I've changed the naming, could you publish it?

Thank you.

### CODE REVIEW

**Comment by thecodester** [comment]
You meant to make Niloofar the author (as well as adding the disclaimer)?

**Comment by mervey45** [comment]
@thecodester I'm the author and the disclaimer should be in this tutorial.

Thank you.

**Comment by thecodester** [comment]
I also see you are not using the new plugin to push to production. I very highly recommend using it.

**Comment by thecodester** [comment]
Your pull request makes her the author. WHen creating a pull request make sure to check the "Files changed" button to see what you are requesting to change. The plugin I believe will help you keep things in sync.

**Comment by mervey45** [comment]
You're right, I'll try it out

**Comment by mervey45** [comment]
Good point, I didn't see it. I'll do it next time.

**Pull request merged**
