### PR TITLE
Edit tutorial

### PR DESCRIPTION
**Pull request by niloofar-flothkoetter**

### CODE REVIEW

**Comment by niloofar-flothkoetter** [comment]
Hi Daniel,
here there are 2 tutorials, one became some updates and the other is a new one.

**Review by thecodester — CHANGES_REQUESTED** [review]
Looks nice:
 
- SAC is not valid synonym for SAP Analytics Cloud
- Can you try to shorten the step names a little (remove "a", remove not essential words)
- In step names you write -query- and -cube- and others -- what is this notation mean? perhaps parentheses unless this is some sort of specific syntax.
- Tile should be title case
- Don't use "etc." and "i.e." in text, if possible. In description, replace it with "and more" or "other ...".
- Are you sure this is beginner?
- Is this part of some group/mission?

You can respond offline to me if needed

**Comment by niloofar-flothkoetter** [comment]
It is a single end-to-end tutorial.
I changed it to intermediate.
other changes are done as well.

**Comment by thecodester** [comment]
The title is still not title case but I will update for you :-) Great tutorial!

**Pull request merged**
