### PR TITLE
Automatic commit: Move datahub-trial-v2-pipelines-part02 from QA to P…

### PR DESCRIPTION
**Pull request by fx5151git**
add additional pipeline information, where the created pipeline could be found

### CODE REVIEW

**Comment by thecodester** [comment]
@fx5151git I see the link to the tutorial is still coded the old way. Can you update?

**Comment by fx5151git** [comment]
But for the commit 5 days ago, I already changed it. Is it not the right way?

**Comment by fx5151git** [comment]
@thecodester

**Comment by thecodester** [comment]
@fx5151git: Links to other tutorials are now coded this way:

[Generate Sensor Data in SAP Data Hub, trial edition 2.4] (datahub-trial-v2-pipelines-part01)

  - Use the title, not the file name
  - DO NOT bold the link

**Comment by fx5151git** [comment]
@thecodester  in the second commit I think it is the right form, or?
image

**Pull request merged**
