### PR TITLE
Automatic commit: Move 'mendix-onboarding' from QA to Production

### PR DESCRIPTION
**Pull request by ShiraManas**
Updated with new screenshots and updated procedure to match the process. Addresses customer bugs.

### CODE REVIEW

**Comment by thecodester** [comment]
Best to communicate through the PR itself. There is another mendix tutorial -- https://developers.sap.com/tutorials/mendix-salesorders.html -- that I see you didn;t update. That one is OK?

**Comment by thecodester** [comment]
A few suggested improvements:

  - Most screenshots, since they have white background with lots of words, would be helped by having a border. To add a border, just add a second ! to the code for an image -- `!My image`

  - The first screenshot in Step 1 comes right after text, not on its own line. Add a blank space.

  - In Step 4, in the middle, when you talk about choosing the CF environment, it's a little word heavy. I think this section would benefit from bullets, ordered list or something.

**Comment by ShiraManas** [comment]
Updated and created a new Pull Request.

**Comment by ShiraManas** [comment]
> Best to communicate through the PR itself. There is another mendix tutorial -- https://developers.sap.com/tutorials/mendix-salesorders.html -- that I see you didn;t update. That one is OK?

I have been asked to update only this tutorial, based on the 2 customer issues on it.

**Pull request merged**
