### PR TITLE
Updated/New MDK tutorials

### PR DESCRIPTION
**Pull request by jitendrakansal**
Updated/New MDK tutorials

### CODE REVIEW

**Comment by thecodester** [comment]
@jitendrakansal Let's try to reduce the commits to production. Once you have all your stuff ready, commit it once. Thanks

**Comment by thecodester** [comment]
@MichaelCzcz We got circleci 404 errors but this PR will solve those.

**Comment by MichaelCzcz** [comment]
Links are wworking now. @thecodester can you please check the two new .md-files?

**Comment by thecodester** [comment]
@jitendrakansal Please check the new tutorials in production after I merge.

@jitendrakansal Do the new tutorials have to be added to a new/existing group?

**Pull request merged**
